### ISSUE TITLE
view的宽和Item的宽不一样时，自动滚动的时候BannerControl 没有滚动

### ISSUE THREAD

**Issue by CymPlus** [wwmz/WMZBanner#10]
.wFrameSet(CGRectMake(0, 100, BannerWitdh, BannerHeight*0.2))  
//自定义item的大小
    .wItemSizeSet(CGSizeMake(BannerWitdh-40, BannerHeight*0.2))
//间距
    .wLineSpacingSet(10)
时，手动滑动可以BannerControl会根着动
自动滚动的时候BannerControl不会

**Comment by wwmz** [comment]
> .wFrameSet(CGRectMake(0, 100, BannerWitdh, BannerHeight_0.2)) //自定义item的大小 .wItemSizeSet(CGSizeMake(BannerWitdh-40, BannerHeight_0.2))
> //间距
> .wLineSpacingSet(10)
> 时，手动滑动可以BannerControl会根着动
> 自动滚动的时候BannerControl不会

已修复 代码更新了 pod没更新
