### ISSUE TITLE
有个小小的问题

### ISSUE THREAD

**Issue by TwelveWirt** [wwmz/WMZBanner#11]
手势左右滑动的时候，如果滑动的距离太小，当前item就会回弹，不能根据手势来滑动到左边或者右边

**Comment by wwmz** [comment]
> 手势左右滑动的时候，如果滑动的距离太小，当前item就会回弹，不能根据手势来滑动到左边或者右边

一般不都是这样吗 分页的效果 距离太小就回到原来的位置

**Comment by doraemontown** [comment]
> > 手势左右滑动的时候，如果滑动的距离太小，当前item就会回弹，不能根据手势来滑动到左边或者右边
> 
> 一般不都是这样吗 分页的效果 距离太小就回到原来的位置

有个快速滑动手势。慢慢的按着左右滑是会回弹，但是当快速左右滑动，就会滚动了。你试试淘宝的轮播。

**Comment by zhangxiongwen** [comment]
如果是快速左右滑动一点点马上松开  回弹的时候为啥没有动画呢？慢速滑动多一点就会有回弹动画了

**Comment by wwmz** [comment]
新增wAddFastScrollAnina属性 可解决

**Comment by doraemontown** [comment]
抱歉，之前运行试了下就回复了，没仔细看。我刚看了下，发现wLineSpacing这个参数导致我上面提出的那个问题，你加的wAddFastScrollAnina，我试下，没效果。我再研究下。

// 我在自定义pageController里测的
WMZBannerParam *param =  BannerParam()
    .wBannerControlColorSet([UIColor lightGrayColor])
    .wBannerControlSelectColorSet([UIColor orangeColor])
    .wFrameSet(CGRectMake(10, 100, BannerWitdh-20, BannerHeight/6))
    .wLineSpacingSet(10)
//    .wAddFastScrollAninaSet(YES)
    .wDataSet([self getData]);
    WMZBannerView *viewOne = [[WMZBannerView alloc]initConfigureWithModel:param];
    [self.view addSubview:viewOne];
