### ISSUE TITLE
pagecontrol设置默认图片和选中图片可以增加一个传图片么？

### ISSUE THREAD

**Issue by gongxinle** [wwmz/WMZBanner#14]
rt.有些需求是需要修改size的，可能是纯色的时候或者是那种可以自己生成的图片，但是这里传的是imagename，就很慌。。。建议不要使用图片名，直接给图片这样适用性更广一点

**Comment by wwmz** [comment]
> rt.有些需求是需要修改size的，可能是纯色的时候或者是那种可以自己生成的图片，但是这里传的是imagename，就很慌。。。建议不要使用图片名，直接给图片这样适用性更广一点

兄弟 可以自定义cell的。。。你自定义就行了

**Comment by gongxinle** [comment]
嗯嗯，其实就是懒，哈哈。我还发现了一个小问题，在实际效果中（横向），cell的y值不是从0开始，会往下偏移一点 暂时没找到什么原因，demo内也是。sectioninset并没有设置上下的边距。有时间了你可以看看。

**Comment by gongxinle** [comment]
因为切了圆角 底部被截断会感觉圆角怪怪的，尝试修改上边距为负值也无效，暂时只能把clipsToBounds改成NO了^_^

**Comment by wwmz** [comment]
> 嗯嗯，其实就是懒，哈哈。我还发现了一个小问题，在实际效果中（横向），cell的y值不是从0开始，会往下偏移一点 暂时没找到什么原因，demo内也是。sectioninset并没有设置上下的边距。有时间了你可以看看。

好的 我有时间看看
