### ISSUE TITLE
轮播图默认设置滚动,只有一张的时候可以设置不让滚动?

### ISSUE THREAD

**Issue by jon521** [wwmz/WMZBanner#15]
只有一张图片时修改滚动属性无反应

**Comment by wwmz** [comment]
> 只有一张图片时修改滚动属性无反应

你手动设置一下 当一张图片的时候  .wRepeatSet(NO)

**Comment by wwmz** [comment]
> 只有一张图片时修改滚动属性无反应

我加个判断吧 GitHub更新了
