### ISSUE TITLE
叠加模式   可以设置被遮挡图片的透明度吗

### ISSUE THREAD

**Issue by dingxiaolong** [wwmz/WMZBanner#18]

**Comment by wwmz** [comment]
可以的 只是我好像没开放出来？你去源码改一下或者等我有时间加一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dingxiaolong <notifications@github.com&gt;
发送时间: 2020年7月22日 17:49
收件人: wwmz/WMZBanner <WMZBanner@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wwmz/WMZBanner] 叠加模式   可以设置被遮挡图片的透明度吗 (#18)

**Comment by wwmz** [comment]
> _No description provided._
你是想要怎么个透明度 遮挡图片依次递减透明 还是遮挡图片固定透明

**Comment by dingxiaolong** [comment]
渐变的,根据滚动距离改变的透明度

**Comment by wwmz** [comment]
> 渐变的,根据滚动距离改变的透明度

刚有空加哈 新增这两个属性
//叠加模式开启透明度变化 default NO
.wCardOverAlphaOpenSet(YES)
 //透明度最小系数 default 0.1 
.wCardOverMinAlphaSet(0.1)
