### ISSUE TITLE
你好,请问可以拓展一下,左右半透明,滑动中间变成alpha = 1效果吗~~

### ISSUE THREAD

**Issue by FaDeve** [wwmz/WMZBanner#2]

**Comment by wwmz** [comment]
新增 wAlpha 属性  默认左右不透明 传0.5 表示左右半透明

**Comment by FaDeve** [comment]
感谢回复!不过使用过程中发现,真机调试,手指刚触摸然后左右滑一下,屏幕会有一闪一闪的效果,就是比如准备向左滑,然后手指立马离开,可以这样复现.(感觉可以改成滑到一定距离再改变数据)

**Comment by wwmz** [comment]
我试了下 没发现呀 @FaDeve
