### ISSUE TITLE
卡片轮播图

### ISSUE THREAD

**Issue by lvyongtao** [wwmz/WMZBanner#21]
卡片轮播图效果中，在设置数据源为1 或者2 的时候未居中

**Comment by wwmz** [comment]
> 卡片轮播图效果中，在设置数据源为1 或者2 的时候未居中

= = 从左往右排 没刻意去居中

**Comment by lvyongtao** [comment]
能否增加属性是否居中，做一下处理。轮播图一般都居中😹

**Comment by wwmz** [comment]
> 能否增加属性是否居中，做一下处理。轮播图一般都居中😹

~ ~

**Comment by wwmz** [comment]
> 能否增加属性是否居中，做一下处理。轮播图一般都居中😹

你设置一下偏移量吧  如果个数是1 或 2的时候 wSectionInset 设置左偏移量就会居中了
