### ISSUE TITLE
建议规范写法

### ISSUE THREAD

**Issue by 295060456** [wwmz/WMZBanner#25]
#import "UIImageView+WebCache.h"这种用尖括号<>
因为我install! 'cocoapods',:deterministic_uuids=>false,generate_multiple_pod_projects: true,disable_input_output_paths: true

的时候，这个是cocoapods 7。1新特性，每一个pods作为一个xcode工程项目进行管理，这个时候你如果不用尖括号<>,我就访问不到，我就要改你的源码，以后我刷新pod或者install的时候就会被冲掉

**Comment by 295060456** [comment]
就像这样

#if __has_include(<Masonry/Masonry.h>)
#import <Masonry/Masonry.h>
#else
#import "Masonry.h"
#endif

**Comment by wwmz** [comment]
> #import "UIImageView+WebCache.h"这种用尖括号<>
> 因为我install! 'cocoapods',:deterministic_uuids=>false,generate_multiple_pod_projects: true,disable_input_output_paths: true
> 
> 的时候，这个是cocoapods 7。1新特性，每一个pods作为一个xcode工程项目进行管理，这个时候你如果不用尖括号<>,我就访问不到，我就要改你的源码，以后我刷新pod或者install的时候就会被冲掉

好的
