### ISSUE TITLE
代码有些水！？没有仔细考虑性能、安全等因素

### ISSUE THREAD

**Issue by hansong8675** [wwmz/WMZBanner#28]
1. 建议更改代码编码方式，不要霍霍啥都不懂的菜鸟
    
就 宏定义吧，官方已经不建议在宏定义中编写很多东西,而且这样写就毫无保留的为逆向留后门，可以说贻害无穷吗，
`#define WMZBannerPropStatementAndPropSetFuncStatement(propertyModifier,className, propertyPointerType, propertyName)           \
@property(nonatomic,propertyModifier)propertyPointerType  propertyName;                                                 \
- (className * (^) (propertyPointerType propertyName)) propertyName##Set;

#define WMZBannerPropSetFuncImplementation(className, propertyPointerType, propertyName)                                       \
- (className * (^) (propertyPointerType propertyName))propertyName##Set{                                                \
return ^(propertyPointerType propertyName) {                                                                            \
_##propertyName = propertyName;                                                                                         \
return self;                                                                                                            \
};                                                                                                                      \
}`

2. 对于成员与属性的应用，要么对.m内开放，要么对App开放，你这个对 拿到你二进制包的人都开放，是担心别人逆向的时候找不到吧，请严格遵守 公有｜ 私有 ｜ 局部公有 来编码
`
//布局方式 frame  必传
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGRect,               wFrame)
//数据源 必传
WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, NSArray*,             wData)
//特殊样式 default 无
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, SpecialStyle,                 wSpecialStyle)

//淡入淡出 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wFadeOpen)
//开启缩放 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wScale)
//开启卡片重叠模式 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wCardOverLap)
//卡片重叠模式开启偏移透明度变化 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wCardOverAlphaOpen)
//叠加模式透明度最小值 defalt 0.1
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wCardOverMinAlpha)
//卡片重叠显示个数 default 4
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger,            wCardOverLapCount)
//背景毛玻璃效果 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wEffect)
//隐藏pageControl default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wHideBannerControl)
//是否允许手势滑动 default YES
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wCanFingerSliding)
//图片不变形铺满 默认 YES
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wImageFill)
//开启无线滚动 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wRepeat)
//开启自动滚动 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wAutoScroll)
//纵向(cell全屏的时候有效) default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wVertical)
//跑马灯(文字效果) default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wMarquee)
//点击左右居中
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wClickCenter)
//中间视图放最上面 default NO
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL,                 wZindex)
//整体间距 默认UIEdgeInsetsMake(0,0, 0, 0)
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIEdgeInsets,         wSectionInset)
//自定义图片圆角 default 5
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wCustomImageRadio)
//整体视图缩放系数 default 1
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wScreenScale)
//毛玻璃背景的高度 (视图的高度*倍数) default 1 范围0~1
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wEffectHeight)
//缩放系数 数值越大缩放越大 default 0.5 卡片叠加效果时默认为0.8
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wScaleFactor)
//左右的透明度 default 1
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wAlpha)
//垂直缩放 数值越大缩放越小 default 400
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wActiveDistance)
//item的size default 视图的宽高 item的width最小为父视图的一半 (为了保证同屏最多显示3个 减少不必要的bug)
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize,               wItemSize)
//item的之间的间距 default 0
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, int,                  wLineSpacing)
//滑动的时候偏移的距离 以倍数计算 default 0.5 正中间
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wContentOffsetX)
//左右相邻item的中心点 default BannerCellPositionCenter
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BannerCellPosition,   wPosition)
//占位图片 默认 -
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, NSString*,            wPlaceholderImage)
//数据源的图片字段 默认 icon
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, NSString*,            wDataParamIconName)
//滚动减速时间 default UIScrollViewDecelerationRateFast
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIScrollViewDecelerationRate,wDecelerationRate)
//自动滚动间隔时间 default 3.0f
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wAutoScrollSecond)
//默认移动到第几个 default 0
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger,            wSelectIndex)
//自定义cell内容 默认是Collectioncell类
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, BannerCellCallBlock,  wMyCell)
//特殊样式SpecialLine 自定义下划线
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, BannerSpecialLine,                  wSpecialCustumLine)
//自定义cell的类名 自定义视图必传 不然会crash
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, NSString*,            wMyCellClassName)
//自定义cell的类名 自定义视图必传 不然会crash 和上面的属性wMyCellClassName 二选一 此属性可以传数组
WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, id,                   wMyCellClassNames)
//系统的圆点颜色  default  ffffff
WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*,             wBannerControlColor)
//系统的圆点选中颜色  default  orange
WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*,             wBannerControlSelectColor)
//自定义安全的圆点图标  default -
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, NSString*,            wBannerControlImage)
//自定义安全的选中圆点图标  default -
WMZBannerPropStatementAndPropSetFuncStatement(copy,   WMZBannerParam, NSString*,            wBannerControlSelectImage)
//自定义安全的圆点图片圆角 default ImageSize/2
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wBannerControlImageRadius)
//自定义安全的圆点图标的size  default (5,5)
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize,               wBannerControlImageSize)`
3.建议加入自动化测试，没有经过测试的使用起来总是有点担心的

**Comment by wwmz** [comment]
> 1. 建议更改代码编码方式，不要霍霍啥都不懂的菜鸟
> 
> 就 宏定义吧，官方已经不建议在宏定义中编写很多东西,而且这样写就毫无保留的为逆向留后门，可以说贻害无穷吗，
> `#define WMZBannerPropStatementAndPropSetFuncStatement(propertyModifier,className, propertyPointerType, propertyName)
> @Property(nonatomic,propertyModifier)propertyPointerType propertyName; \
> 
> * (className * (^) (propertyPointerType propertyName)) propertyName##Set;
> 
> #define WMZBannerPropSetFuncImplementation(className, propertyPointerType, propertyName) \
> 
> * (className * (^) (propertyPointerType propertyName))propertyName##Set{                                                
>   return ^(propertyPointerType propertyName) {                                                                            
>   _##propertyName = propertyName;                                                                                         
>   return self;                                                                                                            
>   };                                                                                                                      
>   }`
> 
> 1. 对于成员与属性的应用，要么对.m内开放，要么对App开放，你这个对 拿到你二进制包的人都开放，是担心别人逆向的时候找不到吧，请严格遵守 公有｜ 私有 ｜ 局部公有 来编码
>    `
>    //布局方式 frame  必传
>    WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGRect,               wFrame)
>    //数据源 必传
>    WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, NSArray*,             wData)
>    //特殊样式 default 无
>    WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, SpecialStyle,                 wSpecialStyle)
> 
> //淡入淡出 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wFadeOpen)
> //开启缩放 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wScale)
> //开启卡片重叠模式 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCardOverLap)
> //卡片重叠模式开启偏移透明度变化 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCardOverAlphaOpen)
> //叠加模式透明度最小值 defalt 0.1
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wCardOverMinAlpha)
> //卡片重叠显示个数 default 4
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger, wCardOverLapCount)
> //背景毛玻璃效果 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wEffect)
> //隐藏pageControl default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wHideBannerControl)
> //是否允许手势滑动 default YES
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCanFingerSliding)
> //图片不变形铺满 默认 YES
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wImageFill)
> //开启无线滚动 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wRepeat)
> //开启自动滚动 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wAutoScroll)
> //纵向(cell全屏的时候有效) default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wVertical)
> //跑马灯(文字效果) default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wMarquee)
> //点击左右居中
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wClickCenter)
> //中间视图放最上面 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wZindex)
> //整体间距 默认UIEdgeInsetsMake(0,0, 0, 0)
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIEdgeInsets, wSectionInset)
> //自定义图片圆角 default 5
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wCustomImageRadio)
> //整体视图缩放系数 default 1
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wScreenScale)
> //毛玻璃背景的高度 (视图的高度_倍数) default 1 范围0~1 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wEffectHeight) //缩放系数 数值越大缩放越大 default 0.5 卡片叠加效果时默认为0.8 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wScaleFactor) //左右的透明度 default 1 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wAlpha) //垂直缩放 数值越大缩放越小 default 400 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wActiveDistance) //item的size default 视图的宽高 item的width最小为父视图的一半 (为了保证同屏最多显示3个 减少不必要的bug) WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize, wItemSize) //item的之间的间距 default 0 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, int, wLineSpacing) //滑动的时候偏移的距离 以倍数计算 default 0.5 正中间 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wContentOffsetX) //左右相邻item的中心点 default BannerCellPositionCenter WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BannerCellPosition, wPosition) //占位图片 默认 - WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString_, wPlaceholderImage)
> //数据源的图片字段 默认 icon
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wDataParamIconName)
> //滚动减速时间 default UIScrollViewDecelerationRateFast
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIScrollViewDecelerationRate,wDecelerationRate)
> //自动滚动间隔时间 default 3.0f
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wAutoScrollSecond)
> //默认移动到第几个 default 0
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger, wSelectIndex)
> //自定义cell内容 默认是Collectioncell类
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, BannerCellCallBlock, wMyCell)
> //特殊样式SpecialLine 自定义下划线
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, BannerSpecialLine, wSpecialCustumLine)
> //自定义cell的类名 自定义视图必传 不然会crash
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wMyCellClassName)
> //自定义cell的类名 自定义视图必传 不然会crash 和上面的属性wMyCellClassName 二选一 此属性可以传数组
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, id, wMyCellClassNames)
> //系统的圆点颜色 default ffffff
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*, wBannerControlColor)
> //系统的圆点选中颜色 default orange
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*, wBannerControlSelectColor)
> //自定义安全的圆点图标 default -
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wBannerControlImage)
> //自定义安全的选中圆点图标 default -
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wBannerControlSelectImage)
> //自定义安全的圆点图片圆角 default ImageSize/2
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wBannerControlImageRadius)
> //自定义安全的圆点图标的size default (5,5)
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize, wBannerControlImageSize)`
> 3.建议加入自动化测试，没有经过测试的使用起来总是有点担心的

1 我是求着你看了吗？
2 我是求着你使用？
3 我怎么编码轮到你在这指指点点？
4 请问你在这装什么？
5 请问你又开源了什么来借鉴一下？
6 出门右拐 我这就一个垃圾组件 不配您看的

**Comment by wwmz** [comment]
> 1. 建议更改代码编码方式，不要霍霍啥都不懂的菜鸟
> 
> 就 宏定义吧，官方已经不建议在宏定义中编写很多东西,而且这样写就毫无保留的为逆向留后门，可以说贻害无穷吗，
> `#define WMZBannerPropStatementAndPropSetFuncStatement(propertyModifier,className, propertyPointerType, propertyName)
> @Property(nonatomic,propertyModifier)propertyPointerType propertyName; \
> 
> * (className * (^) (propertyPointerType propertyName)) propertyName##Set;
> 
> #define WMZBannerPropSetFuncImplementation(className, propertyPointerType, propertyName) \
> 
> * (className * (^) (propertyPointerType propertyName))propertyName##Set{                                                
>   return ^(propertyPointerType propertyName) {                                                                            
>   _##propertyName = propertyName;                                                                                         
>   return self;                                                                                                            
>   };                                                                                                                      
>   }`
> 
> 1. 对于成员与属性的应用，要么对.m内开放，要么对App开放，你这个对 拿到你二进制包的人都开放，是担心别人逆向的时候找不到吧，请严格遵守 公有｜ 私有 ｜ 局部公有 来编码
>    `
>    //布局方式 frame  必传
>    WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGRect,               wFrame)
>    //数据源 必传
>    WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, NSArray*,             wData)
>    //特殊样式 default 无
>    WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, SpecialStyle,                 wSpecialStyle)
> 
> //淡入淡出 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wFadeOpen)
> //开启缩放 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wScale)
> //开启卡片重叠模式 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCardOverLap)
> //卡片重叠模式开启偏移透明度变化 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCardOverAlphaOpen)
> //叠加模式透明度最小值 defalt 0.1
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wCardOverMinAlpha)
> //卡片重叠显示个数 default 4
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger, wCardOverLapCount)
> //背景毛玻璃效果 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wEffect)
> //隐藏pageControl default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wHideBannerControl)
> //是否允许手势滑动 default YES
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wCanFingerSliding)
> //图片不变形铺满 默认 YES
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wImageFill)
> //开启无线滚动 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wRepeat)
> //开启自动滚动 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wAutoScroll)
> //纵向(cell全屏的时候有效) default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wVertical)
> //跑马灯(文字效果) default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wMarquee)
> //点击左右居中
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wClickCenter)
> //中间视图放最上面 default NO
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BOOL, wZindex)
> //整体间距 默认UIEdgeInsetsMake(0,0, 0, 0)
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIEdgeInsets, wSectionInset)
> //自定义图片圆角 default 5
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wCustomImageRadio)
> //整体视图缩放系数 default 1
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wScreenScale)
> //毛玻璃背景的高度 (视图的高度_倍数) default 1 范围0~1 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wEffectHeight) //缩放系数 数值越大缩放越大 default 0.5 卡片叠加效果时默认为0.8 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wScaleFactor) //左右的透明度 default 1 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wAlpha) //垂直缩放 数值越大缩放越小 default 400 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wActiveDistance) //item的size default 视图的宽高 item的width最小为父视图的一半 (为了保证同屏最多显示3个 减少不必要的bug) WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize, wItemSize) //item的之间的间距 default 0 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, int, wLineSpacing) //滑动的时候偏移的距离 以倍数计算 default 0.5 正中间 WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wContentOffsetX) //左右相邻item的中心点 default BannerCellPositionCenter WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, BannerCellPosition, wPosition) //占位图片 默认 - WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString_, wPlaceholderImage)
> //数据源的图片字段 默认 icon
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wDataParamIconName)
> //滚动减速时间 default UIScrollViewDecelerationRateFast
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, UIScrollViewDecelerationRate,wDecelerationRate)
> //自动滚动间隔时间 default 3.0f
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wAutoScrollSecond)
> //默认移动到第几个 default 0
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, NSInteger, wSelectIndex)
> //自定义cell内容 默认是Collectioncell类
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, BannerCellCallBlock, wMyCell)
> //特殊样式SpecialLine 自定义下划线
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, BannerSpecialLine, wSpecialCustumLine)
> //自定义cell的类名 自定义视图必传 不然会crash
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wMyCellClassName)
> //自定义cell的类名 自定义视图必传 不然会crash 和上面的属性wMyCellClassName 二选一 此属性可以传数组
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, id, wMyCellClassNames)
> //系统的圆点颜色 default ffffff
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*, wBannerControlColor)
> //系统的圆点选中颜色 default orange
> WMZBannerPropStatementAndPropSetFuncStatement(strong, WMZBannerParam, UIColor*, wBannerControlSelectColor)
> //自定义安全的圆点图标 default -
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wBannerControlImage)
> //自定义安全的选中圆点图标 default -
> WMZBannerPropStatementAndPropSetFuncStatement(copy, WMZBannerParam, NSString*, wBannerControlSelectImage)
> //自定义安全的圆点图片圆角 default ImageSize/2
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat, wBannerControlImageRadius)
> //自定义安全的圆点图标的size default (5,5)
> WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGSize, wBannerControlImageSize)`
> 3.建议加入自动化测试，没有经过测试的使用起来总是有点担心的

我怎么写关你毛事啊 我求你用了吗

**Comment by wwmz** [comment]
九年义务教育漏网之鱼
