### ISSUE TITLE
wScreenScale这个属性没有实现

### ISSUE THREAD

**Issue by YDBlog** [wwmz/WMZBanner#3]
wScreenScale功能没有实现，请完善

**Comment by wwmz** [comment]
好像没这个属性呀

**Comment by YDBlog** [comment]
不好意思。确实没有这个属性。不知道作者能不能完善一下这个功能需求（这个屏幕缩放比wScreenScale 影响所有View的宽高和所有view的UIEdgeInsets）。谢谢

**Comment by wwmz** [comment]
不知道什么样的效果哦 有图片吗

**Comment by YDBlog** [comment]
效果图倒是没有。这个需求使用的场景是：假设现在真机使用的是iphone4屏幕下（屏幕尺寸是320x480）的布局，一个view的CGRect是（50，40，100，100），如果这个代码运行到另一种屏幕下，我只需要通过设置一个缩放比例系数就行，比如scale是1/4,则这个view的CGRect就变成（50/4,40/4,100/4,100/4）。我举的只是一个view，其实理论上这个缩放比例系数是全局的，控制所有view的宽和高以及UIEdgeInsets的。

**Comment by wwmz** [comment]
已增加wScreenScale参数 default 1   范围0~1之间  包括origin位置也缩放

**Comment by YDBlog** [comment]
👍

**Comment by wwmz** [comment]
可以用的话点个star支持一下哦~ ~2333
