### ISSUE TITLE
我设置了循环 当我设置滚动到当前某个Cell时  会出现往回滚到头无法循环的情况

### ISSUE THREAD

**Issue by ManBuTianYa** [wwmz/WMZBanner#30]
![image](https://user-images.githubusercontent.com/16189552/101114122-c8741600-361b-11eb-9e27-5ffddc4bda92.png)
![image](https://user-images.githubusercontent.com/16189552/101114252-0e30de80-361c-11eb-8c9d-ea1524783dd5.png)
![image](https://user-images.githubusercontent.com/16189552/101114435-6c5dc180-361c-11eb-93b3-b81e05448940.png)

注释的代码是我暂时解决的方法

**Comment by zinkLin** [comment]
不用自己写滚动，
WMZBannerParam直接设置
.wClickCenterSet(YES) 即可把点击的cell 滚动到中间

**Comment by ManBuTianYa** [comment]
我是这样设置的   我用[self.bannerView scrolToPath:path animated:NO];设置滚动到0的时候就到头了，无法忘左滚动
