### ISSUE TITLE
Demo中跑马灯效果 感觉图片有抖动晃眼，体验不怎么好，性能可否优化下？

### ISSUE THREAD

**Issue by heliang219** [wwmz/WMZBanner#32]

**Comment by wwmz** [comment]
> _No description provided._

更新至1.1.7了 看一下

**Comment by heliang219** [comment]
更新了 好像没啥效果 还是会掉帧啊

**Comment by wwmz** [comment]
> 更新了 好像没啥效果 还是会掉帧啊

//速率
    .wMarqueeRateSet(5); 速率设置慢一点看看 我怎么没看出来掉帧。。。

**Comment by heliang219** [comment]
是真机上看的吗？看不出有抖动晃眼的感觉？？？

**Comment by heliang219** [comment]
直接运行的demo demo上设置的就是5秒

**Comment by wwmz** [comment]
> 是真机上看的吗？看不出有抖动晃眼的感觉？？？

模拟器看的 = = 我真机瞅一瞅

**Comment by wwmz** [comment]
> 直接运行的demo demo上设置的就是5秒

1.1.8 更新下 不掉帧了 不过目前无法用手去停止拖动 后面有时间再看看吧。。

**Comment by heliang219** [comment]
我试了下 效果比之前好些了 但是还是会有 大侠你如果有时间再认真弄下吧

**Comment by wwmz** [comment]
> 我试了下 效果比之前好些了 但是还是会有 大侠你如果有时间再认真弄下吧

没掉帧了吧 。。我真机都看不出来了。。

**Comment by heliang219** [comment]
你看不出来？我是看得有闪的感觉  我iPhone8 可能是你机型性能高些看不出来吧

**Comment by wwmz** [comment]
> 你看不出来？我是看得有闪的感觉 我iPhone8 可能是你机型性能高些看不出来吧

1.1.9再更新一哈 重新支持手动拖动停止+再优化了一下效果

**Comment by heliang219** [comment]
嗯 试了下 比之前好很多了  也许是我过于追求完美 我盯着看的话还有那么一丁点点 但是已经可以打99分了
