### ISSUE TITLE
 我们有个需求，是纵向跑马灯，但是我用本框架，速度还是太快了

### ISSUE THREAD

**Issue by 295060456** [wwmz/WMZBanner#34]
//开启跑马灯效果
//    .wMarqueeSet(YES)
    //跑马灯速度
    .wMarqueeRateSet(.167)  这个速度再低就不动了
    //开启纵向
    .wVerticalSet(YES)

**Comment by 295060456** [comment]
问题出在这里：
![image](https://user-images.githubusercontent.com/13795605/107117733-ea557780-68ae-11eb-92e5-f575a0a59bcb.png)
你尝试将0.1 和 10 分别代入 
    //跑马灯速度
    .wMarqueeRateSet(10)
在上图打断点看到相关的值不正常

我现在分析UI临界触发的问题，不想涉及的范围过大，我现在改timer的频率，以求达到我的效果。

**Comment by 295060456** [comment]
可惜了：
![image](https://user-images.githubusercontent.com/13795605/107117795-4d470e80-68af-11eb-9139-0fe74a3e1411.png)
![image](https://user-images.githubusercontent.com/13795605/107117796-53d58600-68af-11eb-8789-cc118ab72b04.png)

**Comment by 295060456** [comment]
作者看到后 这个地方优化一下哦

**Comment by 295060456** [comment]
![image](https://user-images.githubusercontent.com/13795605/107119844-b719e500-68bc-11eb-867b-6549a1d8f7c9.png)
这些问题你处理下，看起来扎眼

**Comment by 295060456** [comment]
我给个建议，你的WMZBannerParam 无非就是封装了block我认为有一定炫技的作用，级别低的人不一定看得懂，不具备普适性。要我来写你这个框架，我就用model，你这个WMZBannerParam想表达的无非是全局的配置。还block回调，小题大做了朋友。

**Comment by wwmz** [comment]
我求你用了吗 不用就出门左拐 装尼玛？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Whiskey_On_The_Rocks&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月6日(星期六) 晚上9:50
收件人:&nbsp;&quot;wwmz/WMZBanner&quot;<WMZBanner@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wwmz/WMZBanner]  我们有个需求，是纵向跑马灯，但是我用本框架，速度还是太快了 (#34)

**Comment by wwmz** [comment]
哪来的傻屌 找什么存在感？我求你用了是不是？找骂是吗？你倒是自己去写啊 在这里秀什么？我怎么写代码需要你指点吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Whiskey_On_The_Rocks&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月6日(星期六) 晚上9:49
收件人:&nbsp;&quot;wwmz/WMZBanner&quot;<WMZBanner@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [wwmz/WMZBanner]  我们有个需求，是纵向跑马灯，但是我用本框架，速度还是太快了 (#34)

**Comment by 295060456** [comment]
作为一个开发，我们正常的参与讨论，大家同道中人，你为什么不虚心接受意见，这样是得不到提高的。
我更愿意看到的是业务上的正常的交流而非人生攻击

**Comment by 295060456** [comment]
你的这个框架  我自己这么修改的
1、//跑马灯的时间频率
WMZBannerPropStatementAndPropSetFuncStatement(assign, WMZBannerParam, CGFloat,              wMarqueeTimeFrequency)
2、WMZBannerPropSetFuncImplementation(WMZBannerParam, CGFloat,                       wMarqueeTimeFrequency)
3、@property(assign,nonatomic)CGFloat marginTime;
4、在- (instancetype)initConfigureWithModel:(WMZBannerParam *)param这里面写：
self.marginTime = self.param.wMarqueeTimeFrequency;

**Comment by wwmz** [comment]
你自己看你最后一段话 像是交流吗？功能代码交流提问 没问题 但是请不要带着指指点点 一副教人写代码的语气 什么叫让你写你会怎么写 我那个本来就是model 自己去看那个宏是不是定义了一个属性  你自己都看不明白 还好意思指点吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Whiskey_On_The_Rocks&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月6日(星期六) 晚上10:10
收件人:&nbsp;&quot;wwmz/WMZBanner&quot;<WMZBanner@noreply.github.com&gt;;
抄送:&nbsp;&quot;WMZ&quot;<925457662@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wwmz/WMZBanner]  我们有个需求，是纵向跑马灯，但是我用本框架，速度还是太快了 (#34)

**Comment by 295060456** [comment]
教育的是

**Comment by 295060456** [comment]
其实兄弟我想表达的是，model用我们熟悉的那种模式，而不是block，你那个其实就是方便链式语法，我看你这个写法以前肯定java转来的，iOS这种写法很少见。所以我为什么说新手看起来头疼呢。而我说的那个问题你也关注下

**Comment by wwmz** [comment]
> 其实兄弟我想表达的是，model用我们熟悉的那种模式，而不是block，你那个其实就是方便链式语法，我看你这个写法以前肯定java转来的，iOS这种写法很少见。所以我为什么说新手看起来头疼呢。而我说的那个问题你也关注下

你自己看下用你平时的model 看能不能用？都说两种用法都可以了？代码都看不懂 还老是什么什么block？param.wMarquee = Yes;
param.wMarqueeRate = 167
param.wVertical = YES 自己看看能不能用再来说三道四ok？再说我喜欢什么习惯 就用啥 还不行？需要迎合你？

**Comment by 295060456** [comment]
高高在上的感觉挺爽的，你就适合干技术，拿死工资，可能你能力比我强，但你这种性格永远成不了气候，记住我说的话。

**Comment by wwmz** [comment]
> 高高在上的感觉挺爽的，你就适合干技术，拿死工资，可能你能力比我强，但你这种性格永远成不了气候，记住我说的话。

嗯 好的 哪里来的滚回哪去ok？
