### ISSUE TITLE
pageControl 只剩一个选中的 

### ISSUE THREAD

**Issue by gongxinle** [wwmz/WMZBanner#36]
如题 应该是iOS14系统就出问题了 之前是好的  demo同样这个问题

**Comment by wwmz** [comment]
> 如题 应该是iOS14系统就出问题了 之前是好的 demo同样这个问题
你的版本应该是很久没更新过了 后面的几个版本已经适配ios14了 你更新至最新呗

**Comment by wwmz** [comment]
> 如题 应该是iOS14系统就出问题了 之前是好的 demo同样这个问题

你的版本应该是很久没更新过了 后面的几个版本已经适配ios14了 你更新至最新呗

**Comment by gongxinle** [comment]
我特意重新拉的代码看的呀！demo确定是最新的嘛？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WMZ <notifications@github.com&gt;
发送时间: 2021年2月26日 22:15
收件人: wwmz/WMZBanner <WMZBanner@noreply.github.com&gt;
抄送: Gxl <549036031@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wwmz/WMZBanner] pageControl 只剩一个选中的  (#36)

**Comment by HanXiaoTeng** [comment]
我这里也是 自定义cell 自定义pagecontrol图片以后 pageControl必须得滑动的时候才显示出来 而且宽度不对 是一个的宽度
