### ISSUE TITLE
自定义卡片

### ISSUE THREAD

**Issue by FrancisChenY** [wwmz/WMZBanner#37]
图片缩放不是等比缩放， 图片被压缩变形了

**Comment by wwmz** [comment]
> 图片缩放不是等比缩放， 图片被压缩变形了

自定义一下cell呗

**Comment by FrancisChenY** [comment]
自定义也是一样吧？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 中午11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wwmz/WMZBanner] 自定义卡片 (#37)





  
图片缩放不是等比缩放， 图片被压缩变形了
  
自定义一下cell呗

**Comment by FrancisChenY** [comment]
我看了你的demo 是自定义的，但是图片还是一样被压缩了哦






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wwmz/WMZBanner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wwmz/WMZBanner] 自定义卡片 (#37)





  
图片缩放不是等比缩放， 图片被压缩变形了
  
自定义一下cell呗

**Comment by wwmz** [comment]
> 自定义也是一样吧？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月25日(星期四) 中午11:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [wwmz/WMZBanner] 自定义卡片 (#37) 图片缩放不是等比缩放， 图片被压缩变形了 自定义一下cell呗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你自定义了 cell都是你自己管理怎么就一样？自己设置一下imageview的contenmode不会？

**Comment by FrancisChenY** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 中午11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wwmz/WMZBanner] 自定义卡片 (#37)





  
自定义也是一样吧？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月25日(星期四) 中午11:22 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [wwmz/WMZBanner] 自定义卡片 (#37) 图片缩放不是等比缩放， 图片被压缩变形了 自定义一下cell呗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你自定义了 cell都是你自己管理怎么就一样？自己设置一下imageview的contenmode不会？

**Comment by YNBand** [comment]
“WMZBannerFlowLayout.m” 中第85行改成 --->  attributes.transform3D = CATransform3DMakeScale(zoom, zoom, 1.0); 即可

**Comment by FrancisChenY** [comment]
感谢作者回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月31日(星期三) 中午12:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wwmz/WMZBanner] 自定义卡片 (#37)





   “WMZBannerFlowLayout.m” 中第85行改成 ---&gt;  attributes.transform3D = CATransform3DMakeScale(zoom, zoom, 1.0); 即可

**Comment by YNBand** [comment]
我不是作者。。。
