### ISSUE TITLE
1.2.0 wCustomControlSet frame 失效

### ISSUE THREAD

**Issue by zhouyijian** [wwmz/WMZBanner#45]
1.1.9 正常，型号 iPad 
iOS 14.5

**Comment by wwmz** [comment]
> 1.1.9 正常，型号 iPad
> iOS 14.5

是frame没改变？

**Comment by wwmz** [comment]
> 1.1.9 正常，型号 iPad
> iOS 14.5

是frame没改变？1.2.0相对于1.1.9来说 啥也没改哦。。。就只是去掉了警告而已。。

**Comment by zhouyijian** [comment]
对的，frame 没变，打断点调试block执行多次，有正确的frame被赋值也有错误的被赋值，最终呈现的是错误的frame，改回1.1.9就正常了

**Comment by zhouyijian** [comment]
CGFloat height = VIPCycleHeight;
            WS(weakSelf);

            CGFloat imaCount = (CGFloat)imgArray.count;
            CGFloat cotrolWidth = imaCount * 18;
            CGFloat x = 0.5 * (KWidth - cotrolWidth);
            CGFloat y = height - 32 - 38;
            
            WMZBannerParam *param = BannerParam()
            .wFrameSet(CGRectMake(0, 0, KWidth, height))
            //item之间的间距
            .wLineSpacingSet(8)
            .wCustomImageRadioSet(12)
            //item的size
            .wItemSizeSet(CGSizeMake(0.4355 * KWidth, height))
            //固定移动的距离 size*倍数
            .wContentOffsetXSet(0.5)
            //默认选中
            .wSelectIndexSet(0)
            .wRepeatSet(YES)
            .wAutoScrollSecondSet(6)
            .wAutoScrollSet(YES)
            //item中心位置
            .wPositionSet(BannerCellPositionCenter)
            //整体左右偏移 item.width的一半 让第一个和最后一个可以居中
            .wSectionInsetSet(UIEdgeInsetsMake(0,BannerWitdh*0.4, 0, BannerWitdh*0.4))
            .wEventClickSet( ^ (id anyID, NSInteger index) {
                [weakSelf clickImage:index];
            })
            .wBannerControlColorSet(kCOLOR_FFFFFF_04)
            .wBannerControlSelectColorSet(kCOLOR_FFFFFF)
            .wBannerControlImageSizeSet(CGSizeMake(6, 6))
            .wBannerControlSelectImageSizeSet(CGSizeMake(6, 6))
            .wBannerControlSelectMarginSet(0)
            .wCustomControlSet(^(UIControl *pageControl) {
                //随意改变xy值
                CGRect rect = pageControl.frame;
                rect.origin.x = x;
                rect.origin.y = y;
                rect.size.width = cotrolWidth;
                pageControl.frame = rect;
            })
            //自定义pageControl的位置
            .wDataSet(imgArray);

**Comment by zhouyijian** [comment]
效果
<img width="547" alt="截屏2021-05-08 下午2 40 56" src="https://user-images.githubusercontent.com/21902742/117529696-8b1d1580-b00b-11eb-9e06-9317819ca988.png">
<img width="559" alt="截屏2021-05-08 下午2 40 49" src="https://user-images.githubusercontent.com/21902742/117529701-9112f680-b00b-11eb-8462-2303e358217f.png">
目测这行代码引起的
<img width="1165" alt="截屏2021-05-08 下午2 41 19" src="https://user-images.githubusercontent.com/21902742/117529730-bdc70e00-b00b-11eb-9d44-1a3401d26c85.png">

删除后正常显示

**Comment by wwmz** [comment]
> 效果
> <img alt="截屏2021-05-08 下午2 40 56" width="547" src="https://user-images.githubusercontent.com/21902742/117529696-8b1d1580-b00b-11eb-9e06-9317819ca988.png">
> <img alt="截屏2021-05-08 下午2 40 49" width="559" src="https://user-images.githubusercontent.com/21902742/117529701-9112f680-b00b-11eb-8462-2303e358217f.png">
> 目测这行代码引起的
> <img alt="截屏2021-05-08 下午2 41 19" width="1165" src="https://user-images.githubusercontent.com/21902742/117529730-bdc70e00-b00b-11eb-9d44-1a3401d26c85.png">
> 
> 删除后正常显示

哦 我知道了 你应该是更新了数据吧  难怪我这重现不了 确实这里更新数据后被重置frame了
