### ISSUE TITLE
如何拿到中间的 cell 呢

### ISSUE THREAD

**Issue by mujinweixiao** [wwmz/WMZBanner#5]
我现在需要在 cell 上面播放视频,怎么才能拿到中间的 cell 呢

**Comment by wwmz** [comment]
wMyCell 自定义cell里 有个indexPath 你如果一页显示3个 中间就是indexPath = 1

**Comment by mujinweixiao** [comment]
NSIndexPath *centerIndexPath = [NSIndexPath indexPathForRow:1 inSection:0];
TemplateChooseBannerCollectionViewCell *centerCell = (TemplateChooseBannerCollectionViewCell *)[collectionView cellForItemAtIndexPath:centerIndexPath];
您的意思是说在wMyCellSet方法里面写上上面的代码获取中间的 cell 嘛

**Comment by mujinweixiao** [comment]
我还是不太理解,方便加个 qq 聊一下嘛,谢谢

**Comment by wwmz** [comment]
925457662   你加我
