### ISSUE TITLE
占位图设置好像没调用方法

### ISSUE THREAD

**Issue by HanXiaoTeng** [wwmz/WMZBanner#6]

**Comment by HanXiaoTeng** [comment]
而且图片数组是一个元素的时候崩溃

**Comment by wwmz** [comment]
1  你是在第一个demoOne里设置占位图的吗 因为那个是自定义的cell内容 所以不生效哦 如果要生效你可以在自定义cell内容里自己设置就好了 ；你如果使用默认的cell就会生效的
2 一个元素崩溃是在外部自定义cell里崩溃的 这个代码是可以自己控制 判断indexPath.row-1的情况的 我是例子没判断哈。

**Comment by HanXiaoTeng** [comment]
好的 我已经自己改完了 谢谢

**Comment by wwmz** [comment]
不客气
