### ISSUE TITLE
自定义UICollectionViewCell，添加到导航控制下的viewController里，轮播cell下移，显示不全

### ISSUE THREAD

**Issue by wyk190576528** [wwmz/WMZBanner#7]

**Comment by wwmz** [comment]
可以截个图看看嘛

**Comment by wyk190576528** [comment]
| |
王亚坤
|
|
wyk190576528@163.com
|
签名由网易邮箱大师定制


在2019年12月16日 14:16，WMZ<notifications@github.com> 写道：

可以截个图看看嘛

**Comment by wwmz** [comment]
看不到 你加我q 发我看看吧

**Comment by wyk190576528** [comment]
我qq190576528

**Comment by wwmz** [comment]
此问题为ios11以下的问题  遇到此问题的时候 在控制器写上   self.automaticallyAdjustsScrollViewInsets = NO;
