### ISSUE TITLE
pageControl自定义坐标位置

### ISSUE THREAD

**Issue by HanXiaoTeng** [wwmz/WMZBanner#8]
pageControl能自定义坐标位置吗 只看到三个位置 我想自定义具体的位置.谢谢

**Comment by wwmz** [comment]
//自定义pageControl的位置   demo的pagecontroll里的styleThree有
      .wCustomControlSet(^(UIPageControl *pageControl) {
          //随意改变xy值
          CGRect rect = pageControl.frame;
          rect.origin.y =  10;
          pageControl.frame = rect;
      })

**Comment by DukeTulip2000** [comment]
请问，在自定义cell模式下，还能改变pagecontrol的位置吗，自己测试是不行，会报错，无法运行

**Comment by wwmz** [comment]
可以啊 自定义cell跟pagecontrol位置无关联的 你报错信息是什么呢

**Comment by HanXiaoTeng** [comment]
.wBannerControlImageSet(@"home_header_func_normal")
            .wBannerControlSelectImageSet(@"home_header_func_selected")
            .wBannerControlImageSizeSet(CGSizeMake(4, 4))
            .wBannerControlSelectImageSizeSet(CGSizeMake(8.5, 4))
            .wCustomControlSet(^(UIPageControl *pageControl) {
                //随意改变xy值
                CGRect rect = pageControl.frame;
                rect.origin.y = 105 - 30;
                pageControl.frame = rect;
            })
我自定义了pageControl 一共是两页 但是默认第一页的时候不显示pagecontrol 滑动一下才显示出来

**Comment by HanXiaoTeng** [comment]
> 可以啊 自定义cell跟pagecontrol位置无关联的 你报错信息是什么呢

.wBannerControlImageSet(@"home_header_func_normal")
.wBannerControlSelectImageSet(@"home_header_func_selected")
.wBannerControlImageSizeSet(CGSizeMake(4, 4))
.wBannerControlSelectImageSizeSet(CGSizeMake(8.5, 4))
.wCustomControlSet(^(UIPageControl *pageControl) {
//随意改变xy值
CGRect rect = pageControl.frame;
rect.origin.y = 105 - 30;
pageControl.frame = rect;
})
我自定义了pageControl 一共是两页 但是默认第一页的时候不显示pagecontrol 滑动一下才显示出来
